### ISSUE TITLE
脚本疑似无法获取Token

### ISSUE THREAD

**Issue by Pil0tXia** [DazeCake/Auto-banjimofang#2]
Job "call_report (trigger: date[2022-09-27 16:21:46 CST], next run at: 2022-09-27 16:21:46 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "d:\Automation\Auto-banjimofang\python\main_modified.py", line 224, in call_report
    report(login(column[index]["phone"], column[index]["pwd"]))
  File "d:\Automation\Auto-banjimofang\python\main_modified.py", line 34, in login
    d_cookie = getcookie(login_url)
  File "d:\Automation\Auto-banjimofang\python\main_modified.py", line 24, in getcookie
    s_token = re.search('name="_token" value="([^"]+)"', s_body.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

似乎是正则匹配没有匹配上
请问有什么头绪吗？

**Comment by Pil0tXia** [comment]
现在 http://www.banjimofang.com/student/login 已经不能账号密码登录了，请问这个项目还能正常使用吗？

**Comment by DazeCake** [comment]
大概是不行了，我们学校已经弃用班级魔方了，这个项目应该不会再更新了
